name: My First Workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World"
          echo "Hi World"
      - name: Print goodbye
        run: |
          echo "Good Bye!"
          echo "Bye!!"
